// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTe6xl3k2z9hFdv8SA0GoI-usciXRujb8',
    appId: '1:797671553506:web:2bd320ae464b36187721bb',
    messagingSenderId: '797671553506',
    projectId: 'fir-faceboook-mobile-app',
    authDomain: 'fir-faceboook-mobile-app.firebaseapp.com',
    storageBucket: 'fir-faceboook-mobile-app.firebasestorage.app',
    measurementId: 'G-FLCKX1LZ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5qyrP02I3aTTwti3dyAtB8ysjQC5U7n8',
    appId: '1:797671553506:android:f21dc11a432aec367721bb',
    messagingSenderId: '797671553506',
    projectId: 'fir-faceboook-mobile-app',
    storageBucket: 'fir-faceboook-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB875tyfAwuP00TagTbxaKycMtYNsNTyQI',
    appId: '1:797671553506:ios:309f595d2b7ae97a7721bb',
    messagingSenderId: '797671553506',
    projectId: 'fir-faceboook-mobile-app',
    storageBucket: 'fir-faceboook-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB875tyfAwuP00TagTbxaKycMtYNsNTyQI',
    appId: '1:797671553506:ios:309f595d2b7ae97a7721bb',
    messagingSenderId: '797671553506',
    projectId: 'fir-faceboook-mobile-app',
    storageBucket: 'fir-faceboook-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTe6xl3k2z9hFdv8SA0GoI-usciXRujb8',
    appId: '1:797671553506:web:4326205c354e8ce17721bb',
    messagingSenderId: '797671553506',
    projectId: 'fir-faceboook-mobile-app',
    authDomain: 'fir-faceboook-mobile-app.firebaseapp.com',
    storageBucket: 'fir-faceboook-mobile-app.firebasestorage.app',
    measurementId: 'G-RWFSEQ5K8Q',
  );
}